#![cfg_attr(not(debug_assertions),windows_subsystem="windows")]
mod vault;
use std::sync::Mutex;
use tauri::{Manager,RunEvent,State};
use vault::{BackupData,BackupSettings,BootstrapStatus,Category,Entry,HistoryRecord,UnlockSecurityState,VaultManager};
#[tauri::command] fn vault_status(state:State<'_,Mutex<VaultManager>>)->Result<BootstrapStatus,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.status()}
#[tauri::command] fn vault_create(master_password:String,confirm_password:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.create(&master_password,&confirm_password)}
#[tauri::command] fn vault_unlock(master_password:String,captcha:Option<String>,state:State<'_,Mutex<VaultManager>>)->Result<Vec<Entry>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.unlock(&master_password,captcha.as_deref())}
#[tauri::command] fn vault_unlock_security_state(state:State<'_,Mutex<VaultManager>>)->Result<UnlockSecurityState,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.security_state()}
#[tauri::command] fn vault_refresh_captcha(state:State<'_,Mutex<VaultManager>>)->Result<String,String>{let mut v=state.lock().map_err(|_|"state lock poisoned".to_string())?;let s=v.security_state()?;if !s.captcha_required{return Err("当前无需验证码".into())}Ok(v.new_captcha())}

#[tauri::command] fn vault_save(entries:Vec<Entry>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.save(&entries)}
#[tauri::command] fn vault_lock(state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.lock()}
#[tauri::command] fn vault_backup(destination:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.backup(&destination)}
#[tauri::command] fn backup_settings_get(state:State<'_,Mutex<VaultManager>>)->Result<BackupSettings,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.backup_settings()}
#[tauri::command] fn backup_settings_set(enabled:bool,directory:Option<String>,retention:usize,state:State<'_,Mutex<VaultManager>>)->Result<BackupSettings,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.set_backup_settings(enabled,directory,retention)}
#[tauri::command] fn backup_now(state:State<'_,Mutex<VaultManager>>)->Result<BackupSettings,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.backup_now()}
#[tauri::command] fn vault_restore(backup_path:String,master_password:String,state:State<'_,Mutex<VaultManager>>)->Result<Vec<Entry>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.restore(&backup_path,&master_password)}
#[tauri::command] fn vault_backup_preview(backup_path:String,master_password:String,state:State<'_,Mutex<VaultManager>>)->Result<BackupData,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.backup_preview(&backup_path,&master_password)}
#[tauri::command] fn vault_backup_merge(backup_path:String,master_password:String,state:State<'_,Mutex<VaultManager>>)->Result<Vec<Entry>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.merge_backup(&backup_path,&master_password)}
#[tauri::command] fn vault_export(entries:Vec<Entry>,destination:String,master_password:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.export_entries(&entries,&destination,&master_password)}
#[tauri::command] fn vault_import(source:String,source_master_password:String,state:State<'_,Mutex<VaultManager>>)->Result<Vec<Entry>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.import_entries(&source,&source_master_password)}
#[tauri::command] fn bulk_import_template(destination:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.write_bulk_import_template(&destination)}
#[tauri::command] fn bulk_import_read(source:String,state:State<'_,Mutex<VaultManager>>)->Result<String,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.read_bulk_import_file(&source)}
#[tauri::command] fn trash_move(entry_id:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.move_to_trash(&entry_id)}
#[tauri::command] fn trash_list(retention_days:i64,state:State<'_,Mutex<VaultManager>>)->Result<Vec<Entry>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.list_trash(retention_days)}
#[tauri::command] fn trash_restore(entry_id:String,state:State<'_,Mutex<VaultManager>>)->Result<Vec<Entry>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.restore_trash(&entry_id)}
#[tauri::command] fn trash_purge(entry_id:Option<String>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.purge_trash(entry_id)}
#[tauri::command] fn category_update(old_name:String,name:String,icon:String,parent_name:Option<String>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.update_category(&old_name,&name,&icon,parent_name.as_deref())}
#[tauri::command] fn category_delete(name:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.delete_category(&name)}
#[tauri::command] fn history_list(entry_id:String,state:State<'_,Mutex<VaultManager>>)->Result<Vec<HistoryRecord>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.history_list(&entry_id)}
#[tauri::command] fn recovery_generate_code(state:State<'_,Mutex<VaultManager>>)->Result<String,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.generate_recovery_code()}
#[tauri::command] fn recovery_enable(recovery_code:String,recovery_questions:Vec<String>,recovery_answers:Vec<String>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.enable_recovery(&recovery_code,&recovery_questions,&recovery_answers)}
#[tauri::command] fn recovery_questions(state:State<'_,Mutex<VaultManager>>)->Result<Vec<String>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.recovery_questions()}
#[tauri::command] fn recovery_verify(recovery_code:String,answers:Vec<String>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.recovery_verify(&recovery_code,&answers)}
#[tauri::command] fn recovery_cancel(state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.recovery_cancel()}
#[tauri::command] fn recovery_set_master(new_password:String,confirm_password:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.recovery_set_master(&new_password,&confirm_password)}
#[tauri::command] fn vault_verify_master(master_password:String,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.verify_master(&master_password)}
#[tauri::command] fn vault_update_security(current_password:String,new_password:Option<String>,new_confirm:Option<String>,questions:Option<Vec<String>>,answers:Option<Vec<String>>,state:State<'_,Mutex<VaultManager>>)->Result<Option<String>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.update_security_settings(&current_password,new_password.as_deref(),new_confirm.as_deref(),questions.as_deref(),answers.as_deref())}
#[tauri::command] fn category_list(state:State<'_,Mutex<VaultManager>>)->Result<Vec<Category>,String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.list_categories()}
#[tauri::command] fn category_create(name:String,icon:String,parent_name:Option<String>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.create_category(&name,&icon,parent_name.as_deref())}
#[tauri::command] fn category_reorder(parent_name:Option<String>,names:Vec<String>,state:State<'_,Mutex<VaultManager>>)->Result<(),String>{state.lock().map_err(|_|"state lock poisoned".to_string())?.reorder_categories(parent_name.as_deref(),&names)}
fn main(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).plugin(tauri_plugin_opener::init()).plugin(tauri_plugin_updater::Builder::new().build()).manage(Mutex::new(VaultManager::new())).invoke_handler(tauri::generate_handler![vault_status,vault_create,vault_unlock,vault_unlock_security_state,vault_refresh_captcha,vault_save,vault_lock,vault_backup,backup_settings_get,backup_settings_set,backup_now,vault_restore,vault_backup_preview,vault_backup_merge,vault_export,vault_import,bulk_import_template,bulk_import_read,trash_move,trash_list,trash_restore,trash_purge,category_update,category_delete,history_list,recovery_generate_code,recovery_enable,recovery_questions,recovery_verify,recovery_cancel,recovery_set_master,vault_verify_master,vault_update_security,category_list,category_create,category_reorder]).build(tauri::generate_context!()).expect("error while building LocalVault").run(|app: &tauri::AppHandle, event: RunEvent|{if matches!(event,RunEvent::Exit){let state=app.state::<Mutex<VaultManager>>();let result=state.lock();if let Ok(mut vault)=result{let _=vault.lock();}}});}
