import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {invoke} from "@tauri-apps/api/core";
import {open,save} from "@tauri-apps/plugin-dialog";
import {check} from "@tauri-apps/plugin-updater";
import {openUrl} from "@tauri-apps/plugin-opener";
import "./styles.css";

type Category={name:string;icon:string};
type Entry={id:string;seq:number;type:string;name:string;username:string;email:string;phone:string;password:string;nickname:string;url:string;notes:string;category:string;tags:string[];favorite:boolean;updatedAt:number;expiresAt:number|null};
type History={changedAt:number;fields:string[]};
type Status={exists:boolean;version:number;recoveryEnabled:boolean};
type BackupData={entries:Entry[];categories:Category[]};
type View="loading"|"create"|"recoverySetup"|"unlock"|"recoveryUnlock"|"recoveryReset"|"vault"|"about";
type Dialog="none"|"category"|"delete"|"recovery"|"discard"|"history"|"import"|"type"|"tag"|"trash"|"categoryEdit"|"credential"|"backupRestore"|"securitySettings";

const TYPES=["平台","网站","系统","APP","其他"];
const DEFAULT_CATS:Category[]=[{name:"默认",icon:"▦"},{name:"工作",icon:"💼"},{name:"财务",icon:"💰"},{name:"社交",icon:"👥"},{name:"开发",icon:"💻"},{name:"其他",icon:"📁"}];
const now=()=>Date.now(),uid=()=>crypto.randomUUID();
function validMasterPassword(p:string){return p.length>=8&&/[a-z]/.test(p)&&/[A-Z]/.test(p)&&/[0-9]/.test(p)&&/[^A-Za-z0-9]/.test(p)}
function score(p:string){if(!p)return 0;let s=Math.min(50,p.length*2);if(/[a-z]/.test(p))s+=8;if(/[A-Z]/.test(p))s+=8;if(/[0-9]/.test(p))s+=8;if(/[^A-Za-z0-9]/.test(p))s+=8;if(/^(password|123456|qwerty|admin|letmein|welcome)/i.test(p))s=Math.min(s,12);if(/(.)\1{3,}/.test(p))s-=15;if(/1234|abcd|qwerty|asdf|zxcv/i.test(p))s-=12;return Math.max(0,Math.min(100,s))}
function emptyEntry(seq:number,category:string):Entry{return{id:uid(),seq,type:"网站",name:"新密码",username:"",email:"",phone:"",password:"",nickname:"",url:"",notes:"",category,tags:[],favorite:false,updatedAt:now(),expiresAt:null}}
function dateInput(ts:number|null){return ts?new Date(ts).toISOString().slice(0,10):""}
function expiryDate(days:number){return now()+days*86400000}

function App(){
 const [view,setView]=useState<View>("loading"),[master,setMaster]=useState(""),[confirm,setConfirm]=useState("");
 const [entries,setEntries]=useState<Entry[]>([]),[categories,setCategories]=useState<Category[]>(DEFAULT_CATS),[selected,setSelected]=useState<string|null>(null);
 const [query,setQuery]=useState(""),[category,setCategory]=useState("全部"),[menu,setMenu]=useState<{x:number;y:number;kind:"blank"|"entry"|"category";id?:string;name?:string}|null>(null);
 const [dialog,setDialog]=useState<Dialog>("none"),[pendingAction,setPendingAction]=useState<(()=>void)|null>(null),[imported,setImported]=useState<Entry[]>([]),[conflictChoice,setConflictChoice]=useState<Record<string,"replace"|"skip">>({}),[categoryName,setCategoryName]=useState(""),[categoryIcon,setCategoryIcon]=useState("📁"),[error,setError]=useState("");
 const [autoLock,setAutoLock]=useState(5),[lastActivity,setLastActivity]=useState(now()),[saveState,setSaveState]=useState("已保存");
 const [recoveryCode,setRecoveryCode]=useState(""),[generatedRecoveryCode,setGeneratedRecoveryCode]=useState("");
 const [questions,setQuestions]=useState(["我最喜欢的一本童年读物是什么？","我自己定义的长期不变短语是什么？","我记得的第一个特别地点是什么？"]),[answers,setAnswers]=useState(["","",""]);
 const [showPass,setShowPass]=useState(false),[editMode,setEditMode]=useState(false),[draft,setDraft]=useState<Entry|null>(null),[multiSelected,setMultiSelected]=useState<string[]>([]),[history,setHistory]=useState<History[]>([]),[dirty,setDirty]=useState(false),[trash,setTrash]=useState<Entry[]>([]),[trashDays,setTrashDays]=useState(30),[categoryEdit,setCategoryEdit]=useState<Category|null>(null),[credentialPassword,setCredentialPassword]=useState(""),[pendingFile,setPendingFile]=useState<string|null>(null),[credentialKind,setCredentialKind]=useState<"export"|"import"|"restore"|"backup"|"settings">("export"),[backupData,setBackupData]=useState<BackupData|null>(null);
 const [securityQuestions,setSecurityQuestions]=useState(["我最喜欢的一本童年读物是什么？","我自己定义的长期不变短语是什么？","我记得的第一个特别地点是什么？"]),[securityAnswers,setSecurityAnswers]=useState(["","",""]),[changeMaster,setChangeMaster]=useState(false),[changeRecovery,setChangeRecovery]=useState(false),[newMaster,setNewMaster]=useState(""),[newConfirm,setNewConfirm]=useState(""),[verifiedMasterPassword,setVerifiedMasterPassword]=useState("");
 const [types,setTypes]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("lv_types")||"null")||TYPES}catch{return TYPES}}),[tags,setTags]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("lv_tags")||"null")||["工作","高频使用","财务相关"]}catch{return ["工作","高频使用","财务相关"]}});

 useEffect(()=>{(async()=>{try{const s=await invoke<Status>("vault_status");setView(s.exists?"unlock":"create")}catch(e){setError(String(e));setView("create")}})()},[]);
 useEffect(()=>{const f=()=>setLastActivity(now());addEventListener("mousemove",f);addEventListener("keydown",f);return()=>{removeEventListener("mousemove",f);removeEventListener("keydown",f)}},[]);
 useEffect(()=>{const id=setInterval(async()=>{if(view==="vault"&&now()-lastActivity>autoLock*60000){await invoke("vault_lock").catch(()=>{});setEntries([]);setSelected(null);setDraft(null);setView("unlock");setMaster("")}},1000);return()=>clearInterval(id)},[view,lastActivity,autoLock]);

 const loadCategories=async()=>{try{const cs=await invoke<Category[]>("category_list");setCategories(cs.length?cs:DEFAULT_CATS)}catch{setCategories(DEFAULT_CATS)}};
 const loadHistory=async(id:string)=>{try{setHistory(await invoke<History[]>("history_list",{entryId:id}))}catch{setHistory([])}};
 const loadRecoveryQuestions=async()=>{try{const qs=await invoke<string[]>("recovery_questions");if(qs.length===3)setQuestions(qs)}catch{}};
 const copyRecoveryCode=async(code:string)=>{try{await navigator.clipboard.writeText(code);setSaveState("Recovery Code 已复制");return true}catch{setError("无法自动复制 Recovery Code，请从提示框中手动保存");return false}};
 const openRecoveryUnlock=async()=>{setError("");await loadRecoveryQuestions();setRecoveryCode("");setAnswers(["","",""]);setView("recoveryUnlock")};
 const createVault=async()=>{setError("");if(!validMasterPassword(master)){setError("主密码必须至少 8 位，并包含数字、大写字母、小写字母和特殊符号");return}if(master!==confirm){setError("两次输入的主密码不一致");return}try{await invoke("vault_create",{masterPassword:master,confirmPassword:confirm});const code=await invoke<string>("recovery_generate_code");setGeneratedRecoveryCode(code);setMaster("");setConfirm("");await loadCategories();setView("recoverySetup")}catch(e){setError(String(e))}};
 const finishRecovery=async()=>{setError("");try{await invoke("recovery_enable",{recoveryCode:generatedRecoveryCode,recoveryQuestions:questions,recoveryAnswers:answers});await copyRecoveryCode(generatedRecoveryCode);setGeneratedRecoveryCode("");setAnswers(["","",""]);setView("vault")}catch(e){setError(String(e))}};
 const unlock=async()=>{setError("");try{const xs=await invoke<Entry[]>("vault_unlock",{masterPassword:master});setEntries(xs.map((e,i)=>({...e,seq:e.seq||i+1,type:e.type||"网站",email:e.email||"",phone:e.phone||"",nickname:e.nickname||"",expiresAt:e.expiresAt??null})));await loadCategories();await loadTrash();setSelected(null);setMaster("");setView("vault")}catch{setError("主密码错误，或 Vault 已损坏/篡改")}};
 const verifyRecovery=async()=>{setError("");try{await invoke("recovery_verify",{recoveryCode,answers});setRecoveryCode("");setAnswers(["","",""]);setNewMaster("");setNewConfirm("");setView("recoveryReset")}catch{setError("恢复验证失败：Recovery Code 或密保答案不正确")}};
 const resetMasterFromRecovery=async()=>{setError("");if(!validMasterPassword(newMaster)){setError("新主密码必须至少 8 位，并包含数字、大写字母、小写字母和特殊符号");return}if(newMaster!==newConfirm){setError("两次输入的新主密码不一致");return}try{await invoke("recovery_set_master",{newPassword:newMaster,confirmPassword:newConfirm});setNewMaster("");setNewConfirm("");setView("unlock");setMaster("");setError("主密码已修改，请使用新主密码验证解锁。")}catch(e){setError(String(e))}};
 const cancelRecoveryReset=async()=>{await invoke("recovery_cancel").catch(()=>{});setNewMaster("");setNewConfirm("");setView("unlock")};
 const openSecuritySettings=async()=>{if(dirty){askDiscard(openSecuritySettings);return}setError("");setCredentialKind("settings");setCredentialPassword("");setDialog("credential")};
 const askDiscard=(action:()=>void|Promise<void>)=>{setPendingAction(()=>action);setDialog("discard")};
 const performLock=async()=>{await invoke("vault_lock").catch(()=>{});setEntries([]);setSelected(null);setDraft(null);setEditMode(false);setDirty(false);setView("unlock");setMaster("")};
 const performAdd=()=>{const c=category==="全部"?"默认":category;const e=emptyEntry(Math.max(0,...entries.map(x=>x.seq||0))+1,c);setSelected(e.id);setDraft(e);setEditMode(true);setDirty(false);setShowPass(false);setMenu(null)};
 const performChoose=(id:string)=>{const e=entries.find(x=>x.id===id);if(!e)return;setSelected(id);setDraft({...e});setEditMode(false);setShowPass(false);setDirty(false);loadHistory(id)};
 const requestAction=(action:()=>void|Promise<void>)=>{if(dirty)askDiscard(action);else void action()};
 const lock=()=>requestAction(performLock);
 const saveEntries=async(xs:Entry[])=>{setSaveState("保存中…");try{await invoke("vault_save",{entries:xs});setEntries(xs);setSaveState("已保存");setDirty(false);return true}catch(e){setSaveState("保存失败");setError(String(e));return false}};
 const add=()=>requestAction(performAdd);
 const choose=(id:string)=>{if(dirty&&selected!==id){askDiscard(()=>performChoose(id));return}performChoose(id)};
 const commitDraft=async()=>{if(!draft)return true;const isNew=!entries.some(e=>e.id===draft.id);const hasContent=[draft.name!=="新密码"?draft.name:"",draft.username,draft.email,draft.phone,draft.password,draft.nickname,draft.url,draft.notes,draft.tags.join("")].some(v=>String(v||"").trim());if(isNew&&!hasContent){setSelected(null);setDraft(null);setEditMode(false);setDirty(false);return true}const updated={...draft,updatedAt:now(),name:draft.name.trim()||"未命名"};const xs=isNew?[updated,...entries]:entries.map(e=>e.id===draft.id?updated:e);const ok=await saveEntries(xs);if(!ok)return false;setDraft(updated);setSelected(updated.id);setEditMode(false);await loadHistory(updated.id);return true};
 const deleteCurrent=async()=>{if(!selected)return;const exists=entries.some(e=>e.id===selected);if(!exists){setSelected(null);setDraft(null);setEditMode(false);setDialog("none");return}try{await invoke("trash_move",{entryId:selected,retentionDays:trashDays});await saveEntries(entries.filter(e=>e.id!==selected));await loadTrash();}catch(e){setError(String(e));return}setSelected(null);setDraft(null);setDialog("none")};
 const loadTrash=async()=>{try{setTrash(await invoke<Entry[]>("trash_list",{retentionDays:trashDays}))}catch{setTrash([])}};
 const restoreTrash=async(id:string)=>{try{const xs=await invoke<Entry[]>("trash_restore",{entryId:id});setEntries(xs);await loadTrash();setDialog("trash")}catch(e){setError(String(e))}};
 const purgeTrash=async(id?:string)=>{try{await invoke("trash_purge",{entryId:id||null});await loadTrash()}catch(e){setError(String(e))}};
 const updateCategory=async()=>{if(!categoryEdit)return;const n=categoryName.trim();if(!n){setError("请输入分类名称");return}try{await invoke("category_update",{oldName:categoryEdit.name,name:n,icon:categoryIcon});const xs=entries.map(e=>e.category===categoryEdit.name?{...e,category:n}:e);await saveEntries(xs);if(category===categoryEdit.name)setCategory(n);await loadCategories();setCategoryEdit(null);setDialog("none")}catch(e){setError(String(e))}};
 const deleteCategory=async(name:string)=>{if(name==="默认"){setError("默认分类不能删除");return}try{const xs=entries.map(e=>e.category===name?{...e,category:"默认"}:e);await invoke("category_delete",{name});await saveEntries(xs);if(category===name)setCategory("全部");await loadCategories();}catch(e){setError(String(e))}};
 const addType=()=>{const n=prompt("输入新的账号类型");if(n&&n.trim()){const v=n.trim();setTypes(a=>{const x=Array.from(new Set([...a,v]));localStorage.setItem("lv_types",JSON.stringify(x));return x})}};
 const addTag=()=>{const n=prompt("输入新的标签");if(n&&n.trim()){const v=n.trim();setTags(a=>{const x=Array.from(new Set([...a,v]));localStorage.setItem("lv_tags",JSON.stringify(x));return x})}};
 const exportEntries=async()=>{try{const p=await save({defaultPath:"LocalVault-仅账号密码.lvx",filters:[{name:"LocalVault 账号密码数据",extensions:["lvx"]}]});if(p){setPendingFile(p);setCredentialKind("export");setCredentialPassword("");setDialog("credential")}}catch(e){setError(String(e))}};
 const importEntries=async()=>{try{const p=await open({multiple:false,directory:false,filters:[{name:"LocalVault 账号密码数据",extensions:["lvx"]}]});if(typeof p!=="string")return;setPendingFile(p);setCredentialKind("import");setCredentialPassword("");setDialog("credential")}catch(e){setError(String(e))}};
 const restore=async()=>{try{const p=await open({multiple:false,directory:false,filters:[{name:"LocalVault 加密备份",extensions:["vault"]}]});if(typeof p!=="string")return;setPendingFile(p);setCredentialKind("restore");setCredentialPassword("");setDialog("credential")}catch(e){setError(String(e))}};
 const confirmCredential=async()=>{const p=pendingFile;const pw=credentialPassword;setError("");try{if(credentialKind==="settings"){await invoke("vault_verify_master",{masterPassword:pw});try{const qs=await invoke<string[]>("recovery_questions");if(qs.length===3)setSecurityQuestions(qs)}catch{}setSecurityAnswers(["","",""]);setChangeMaster(false);setChangeRecovery(false);setNewMaster("");setNewConfirm("");setVerifiedMasterPassword(pw);setCredentialPassword("");setDialog("securitySettings");return}if(!p){setDialog("none");return}if(credentialKind==="backup"){await invoke("vault_backup",{destination:p,masterPassword:pw});setSaveState("已导出完整备份");setDialog("none")}else if(credentialKind==="export"){await invoke("vault_export",{entries,destination:p,masterPassword:pw});setSaveState("已导出仅账号密码");setDialog("none")}else if(credentialKind==="import"){const xs=await invoke<Entry[]>("vault_import",{source:p,sourceMasterPassword:pw});const existing=new Map(entries.map(e=>[`${e.type}::${e.username}`.toLowerCase(),e]));const choices:Record<string,"replace"|"skip">={};for(const e of xs){const key=`${e.type}::${e.username}`.toLowerCase();if(existing.has(key)&&e.username)choices[e.id]="skip";}setImported(xs);setConflictChoice(choices);setPendingFile(null);setCredentialPassword("");setDialog("import")}else{const data=await invoke<BackupData>("vault_backup_preview",{backupPath:p,masterPassword:pw});setBackupData(data);if(view==="vault"){setDialog("backupRestore")}else{const xs=await invoke<Entry[]>("vault_restore",{backupPath:p,masterPassword:pw});setEntries(xs);await loadCategories();await loadTrash();setSelected(null);setDraft(null);setEditMode(false);setDirty(false);setMaster("");setPendingFile(null);setCredentialPassword("");setBackupData(null);setDialog("none");setView("vault")}}}catch(e){setError(String(e))}};
 const saveSecuritySettings=async()=>{if(changeMaster&&!validMasterPassword(newMaster)){setError("新主密码必须至少 8 位，并包含数字、大写字母、小写字母和特殊符号");return}if(changeMaster&&newMaster===verifiedMasterPassword){setError("新主密码不能与旧主密码相同");return}if(!changeMaster&&!changeRecovery){setError("请至少选择一项修改");return}if(changeMaster&&newMaster!==newConfirm){setError("两次输入的新主密码不一致");return}if(changeRecovery&&securityAnswers.some(a=>!a.trim())){setError("每个密保答案不能为空");return}setError("");try{const code=await invoke<string|null>("vault_update_security",{currentPassword:verifiedMasterPassword,newPassword:changeMaster?newMaster:null,newConfirm:changeMaster?newConfirm:null,questions:changeRecovery?securityQuestions:null,answers:changeRecovery?securityAnswers:null});if(code){await copyRecoveryCode(code);alert(`新的 Recovery Code：\n\n${code}\n\n旧 Recovery Code 已失效。请立即离线保存。`)}setCredentialPassword("");setVerifiedMasterPassword("");setNewMaster("");setNewConfirm("");setChangeMaster(false);setChangeRecovery(false);setDialog("none");setSaveState("安全设置已更新")}catch(e){setError(String(e))}};
 const restoreBackupReplace=async()=>{const p=pendingFile;const pw=credentialPassword;if(!p)return;setError("");try{const xs=await invoke<Entry[]>("vault_restore",{backupPath:p,masterPassword:pw});setEntries(xs);await loadCategories();await loadTrash();setSelected(null);setDraft(null);setEditMode(false);setDirty(false);setMaster("");setPendingFile(null);setCredentialPassword("");setBackupData(null);setDialog("none");setView("vault")}catch(e){setError(String(e))}};
 const restoreBackupMerge=async()=>{const p=pendingFile;const pw=credentialPassword;if(!p||!backupData)return;setError("");try{const xs=await invoke<Entry[]>("vault_backup_merge",{backupPath:p,masterPassword:pw});setEntries(xs);await loadCategories();await loadTrash();setSelected(null);setDraft(null);setEditMode(false);setDirty(false);setMaster("");setPendingFile(null);setCredentialPassword("");setBackupData(null);setDialog("none");setSaveState("已合并 Vault 备份")}catch(e){setError(String(e))}};
 const batchDelete=async()=>{if(!multiSelected.length)return;setDialog("delete");};
 const applyBatchDelete=async()=>{const ids=new Set(multiSelected);try{for(const id of ids)await invoke("trash_move",{entryId:id,retentionDays:trashDays});await saveEntries(entries.filter(e=>!ids.has(e.id)));await loadTrash();setMultiSelected([]);setSelected(null);setDraft(null);setDialog("none")}catch(e){setError(String(e))}};
 const applyImport=async()=>{const existing=new Map(entries.map(e=>[`${e.type}::${e.username}`.toLowerCase(),e]));let xs=[...entries];const missingCats=Array.from(new Set(imported.map(e=>e.category||"默认").filter(c=>!categories.some(x=>x.name===c))));try{for(const c of missingCats){await invoke("category_create",{name:c,icon:"📁"})}if(missingCats.length)await loadCategories()}catch(e){setError(String(e));return}for(const e of imported){const key=`${e.type}::${e.username}`.toLowerCase();const old=existing.get(key);if(old&&e.username){if(conflictChoice[e.id]==="replace")xs=xs.map(x=>x.id===old.id?{...e,id:old.id,seq:old.seq}:x);else continue}else{const max=Math.max(0,...xs.map(x=>x.seq||0));xs=[{...e,seq:max+1},...xs]}}const ok=await saveEntries(xs);if(!ok)return;setImported([]);setDialog("none")};
 const createCategory=async()=>{const n=categoryName.trim();if(!n){setError("请输入分类名称");return}try{await invoke("category_create",{name:n,icon:categoryIcon});await loadCategories();setCategory(n);setCategoryName("");setDialog("none")}catch(e){setError(String(e))}};
 const backup=async()=>{try{const p=await save({defaultPath:"LocalVault-完整备份.vault",filters:[{name:"LocalVault 加密备份",extensions:["vault"]}]});if(p){setPendingFile(p);setCredentialKind("backup");setCredentialPassword("");setDialog("credential")}}catch(e){setError(String(e))}};
 const checkUpdate=async()=>{try{const u=await check();alert(u?`发现新版本：${u.version}`:"当前已是最新版本")}catch(e){alert("检查更新失败："+String(e))}};
 const filtered=entries.filter(e=>(category==="全部"||category==="收藏"&&e.favorite||e.category===category)&&(e.name+" "+e.username+" "+e.email+" "+e.phone+" "+e.nickname+" "+e.url+" "+e.category+" "+e.tags.join(" ")+" "+e.type).toLowerCase().includes(query.toLowerCase()));
 const current=entries.find(e=>e.id===selected);
 const weak=entries.filter(e=>score(e.password)<40).length;
 const reused=entries.filter((e,i)=>e.password&&entries.findIndex(x=>x.password===e.password)!==i).length;
 const expiring=(e:Entry)=>e.expiresAt!==null&&e.expiresAt<=now()+7*86400000;
 const setDraftField=(k:keyof Entry,v:any)=>{if(!draft)return;setDraft({...draft,[k]:v});setDirty(true)};
 const targetHref=(v:string)=>/^https?:\/\//i.test(v)?v:`https://${v}`;
 const canOpenUrl=(v:string)=>/^https?:\/\//i.test(v)||/^www\./i.test(v)||/^\d{1,3}(?:\.\d{1,3}){3}(?::\d+)?(?:\/|$)/.test(v)||/^[a-z0-9.-]+\.[a-z]{2,}(?:\/|$)/i.test(v);
 const openSavedUrl=async(v:string)=>{try{await openUrl(targetHref(v))}catch(e){setError("无法打开网址："+String(e))}};

 if(view==="loading")return <div className="splash"><div className="logo">🔐</div><h1>LocalVault</h1><p>正在初始化…</p></div>;
 if(view==="create")return <Auth title="创建你的 Vault" subtitle="首次启动仅在本机创建加密 Vault。"><input autoFocus type="password" placeholder="主密码（至少 8 位，含数字/大小写字母/特殊符号）" value={master} onChange={e=>setMaster(e.target.value)}/><input type="password" placeholder="再次输入主密码" value={confirm} onChange={e=>setConfirm(e.target.value)}/><Meter value={score(master)}/><button onClick={createVault}>创建 Vault</button><button className="secondary" onClick={restore}>恢复已有 Vault</button>{error&&<div className="error">{error}</div>}</Auth>;
 if(view==="recoverySetup")return <Auth title="设置恢复方式" subtitle="保存离线 Recovery Code，并设置三组本地问题。"><div className="codebox">{generatedRecoveryCode}</div><button className="secondary" onClick={()=>void copyRecoveryCode(generatedRecoveryCode)}>复制 Recovery Code</button>{questions.map((q,i)=><label className="left" key={i}>问题 {i+1}<input value={q} onChange={e=>{const x=[...questions];x[i]=e.target.value;setQuestions(x)}}/><input value={answers[i]} placeholder="答案（不能为空，可使用中文）" onChange={e=>{const x=[...answers];x[i]=e.target.value;setAnswers(x)}}/></label>)}<button onClick={finishRecovery}>保存恢复设置并进入</button><button className="secondary" onClick={()=>setView("vault")}>稍后设置</button>{error&&<div className="error">{error}</div>}</Auth>;
 if(view==="unlock")return <Auth title="解锁 LocalVault" subtitle="请输入主密码解锁本地加密数据库。"><input autoFocus type="password" placeholder="主密码" value={master} onChange={e=>setMaster(e.target.value)} onKeyDown={e=>e.key==="Enter"&&unlock()}/><button onClick={unlock}>解锁</button><button className="link" onClick={openRecoveryUnlock}>找回主密码</button>{error&&<div className="error">{error}</div>}</Auth>;
 if(view==="recoveryUnlock")return <Auth title="找回主密码" subtitle="使用 Recovery Code + 三组密保验证身份。验证通过后，请设置新的主密码。"><input value={recoveryCode} onChange={e=>setRecoveryCode(e.target.value)} placeholder="Recovery Code"/>{questions.map((q,i)=><label className="left" key={i}>Q{i+1}. {q}<input value={answers[i]} onChange={e=>{const x=[...answers];x[i]=e.target.value;setAnswers(x)}}/></label>)}<button onClick={verifyRecovery}>验证身份</button><button className="secondary" onClick={async()=>{await invoke("recovery_cancel").catch(()=>{});setView("unlock")}}>返回</button>{error&&<div className="error">{error}</div>}</Auth>;
 if(view==="recoveryReset")return <Auth title="设置新主密码" subtitle="验证已通过。请输入新的主密码，修改完成后必须重新使用新密码验证。"><input autoFocus type="password" placeholder="新主密码（至少 8 位，含数字/大小写字母/特殊符号）" value={newMaster} onChange={e=>setNewMaster(e.target.value)}/><input type="password" placeholder="再次输入新主密码" value={newConfirm} onChange={e=>setNewConfirm(e.target.value)}/><Meter value={score(newMaster)}/><button onClick={resetMasterFromRecovery}>修改主密码</button><button className="secondary" onClick={cancelRecoveryReset}>取消</button>{error&&<div className="error">{error}</div>}</Auth>;
 if(view==="about")return <div className="about"><div className="aboutCard"><div className="logo">🔐</div><h1>LocalVault</h1><p>本地优先密码保险库</p><dl><dt>版本</dt><dd>1.6.2</dd><dt>数据库</dt><dd>SQLite</dd><dt>KDF</dt><dd>Argon2id</dd><dt>AEAD</dt><dd>XChaCha20-Poly1305</dd></dl><button onClick={()=>setView("vault")}>返回</button></div></div>;

 return <div className="app" onContextMenu={e=>{const t=e.target as HTMLElement;if(!t.closest("input,textarea,button,.editor,.context")){e.preventDefault();setMenu({x:e.clientX,y:e.clientY,kind:"blank"})}}} onClick={()=>setMenu(null)}>
  <header><b>🔐 LocalVault <span className="pill">V1.6</span></b><input className="topsearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称、账号、网址、标签…"/><span className="status">{saveState}</span><button className="ghost" onClick={lock}>🔒 锁定</button></header>
  <aside><button className="new" onClick={add}>＋ 新建密码</button><p className={category==="全部"?"active":""} onClick={()=>requestAction(()=>setCategory("全部"))}>全部 <span>{entries.length}</span></p><p className={category==="收藏"?"active":""} onClick={()=>requestAction(()=>setCategory("收藏"))}>★ 收藏 <span>{entries.filter(e=>e.favorite).length}</span></p><hr/><small>分类</small>{categories.map(c=><p key={c.name} className={category===c.name?"active":""} onClick={()=>requestAction(()=>setCategory(c.name))} onContextMenu={ev=>{ev.preventDefault();ev.stopPropagation();setMenu({x:ev.clientX,y:ev.clientY,kind:"category",name:c.name})}}><span className="catIcon">{c.icon}</span>{c.name}<span>{entries.filter(e=>e.category===c.name).length}</span></p>)}<button className="utility" onClick={()=>{setCategoryName("");setCategoryIcon("📁");setDialog("category")}}>＋ 新建分类</button><button className="utility" onClick={()=>requestAction(()=>{loadTrash();setDialog("trash")})}>♻ 回收站 <span>{trash.length}</span></button><hr/><small>安全中心</small><p>弱密码 <span>{weak}</span></p><p>重复密码 <span>{reused}</span></p><hr/><label>自动锁定<select value={autoLock} onChange={e=>setAutoLock(+e.target.value)}><option value={1}>1 分钟</option><option value={5}>5 分钟</option><option value={10}>10 分钟</option><option value={30}>30 分钟</option></select></label><button className="utility" title="完整复制当前 Vault 文件；恢复时需要原 Vault 主密码。" onClick={backup}>完整备份</button><button className="utility" title="只导出密码条目，可在另一台电脑导入；导出时需要原 Vault 主密码。" onClick={exportEntries}>仅导出账号密码</button><button className="utility" title="导入另一台电脑导出的 LVX 加密数据；需要原电脑主密码。" onClick={importEntries}>导入账号密码</button><button className="utility" title="恢复完整 Vault 备份；会先验证主密码，并可选择合并或替换当前 Vault。" onClick={()=>requestAction(restore)}>导入完整备份</button><button className="utility" onClick={openSecuritySettings}>密保及密码修改</button><button className="utility" onClick={checkUpdate}>检查更新</button><button className="utility" onClick={()=>requestAction(()=>setView("about"))}>关于</button></aside>
  <main onClick={e=>{const t=e.target as HTMLElement;if(!t.closest(".item,.editor,.listToolbar")){setMenu(null)}}}><section className="list"><div className="listToolbar"><label className="selectAll"><input type="checkbox" checked={filtered.length>0&&filtered.every(e=>multiSelected.includes(e.id))} onChange={ev=>setMultiSelected(ev.target.checked?Array.from(new Set([...multiSelected,...filtered.map(e=>e.id)])):multiSelected.filter(id=>!filtered.some(e=>e.id===id)))} /> 全选</label><span>{filtered.length} 条记录</span>{multiSelected.length>0&&<><b>已选 {multiSelected.length}</b><button className="dangerBtn" onClick={batchDelete}>批量删除</button></>}</div>{filtered.map(e=><div key={e.id} className={`item ${selected===e.id?"selected":""} ${expiring(e)?"expiring":""}`} onClick={()=>choose(e.id)} onContextMenu={ev=>{ev.preventDefault();ev.stopPropagation();setMenu({x:ev.clientX,y:ev.clientY,kind:"entry",id:e.id})}}><div className="itemMain"><input className="selectBox" type="checkbox" checked={multiSelected.includes(e.id)} onChange={ev=>{ev.stopPropagation();setMultiSelected(a=>ev.target.checked?[...a,e.id]:a.filter(x=>x!==e.id))}} onClick={ev=>ev.stopPropagation()}/><div className="seq">#{e.seq}</div><div><b>{e.name||"未命名"}</b><span>{e.nickname||e.username||e.email||"无账号信息"}</span><small>{e.type} · {e.category}</small></div></div><div className="itemMeta">{e.favorite&&<i title="已收藏" className="favoriteMark">★</i>}{score(e.password)<40&&<i title="弱密码" className="weakMark">⚠</i>}{expiring(e)&&<i title="7天内过期">⚠</i>}<em>{score(e.password)}</em></div></div>)}{!filtered.length&&<div className="empty">暂无密码条目<br/><small>在空白区域右键添加</small></div>}</section><section className="editor">{draft?<Editor entry={draft} entries={entries} categories={categories} types={types} tags={tags} editMode={editMode} setEditMode={setEditMode} dirty={dirty} setDirty={setDirty} showPass={showPass} setShowPass={setShowPass} onChange={setDraftField} onSave={commitDraft} onCancel={()=>{const original=entries.find(e=>e.id===draft.id);if(original)setDraft({...original});else{setSelected(null);setDraft(null)}setEditMode(false);setDirty(false)}} onDelete={()=>setDialog("delete")} onHistory={()=>{loadHistory(draft.id);setDialog("history")}} targetHref={targetHref} onAddType={addType} onAddTag={addTag}/>:<div className="editor-empty"><div className="editor-empty-icon">🔐</div><h2>选择一个密码</h2><p>查看时默认只读；点击“编辑密码”后才允许修改。</p></div>}</section></main>
  {menu&&<div className="context" style={{left:Math.min(menu.x,window.innerWidth-220),top:Math.min(menu.y,window.innerHeight-210)}} onClick={e=>e.stopPropagation()}>{menu.kind==="entry"?<><strong>密码操作</strong><button onClick={()=>{choose(menu.id!);setMenu(null)}}>查看</button><button onClick={()=>{choose(menu.id!);setTimeout(()=>setEditMode(true),0);setMenu(null)}}>✎ 编辑</button><button onClick={()=>{setSelected(menu.id!);setMenu(null);setDialog("delete")}}>删除</button></>:menu.kind==="category"?<><strong>分类操作</strong><button onClick={()=>{setCategory(menu.name||"全部");setMenu(null)}}>查看</button><button onClick={()=>{const c=categories.find(x=>x.name===menu.name);if(c){setCategoryEdit(c);setCategoryName(c.name);setCategoryIcon(c.icon);setDialog("categoryEdit")}setMenu(null)}}>编辑分类</button><button className="dangerBtn" onClick={()=>{deleteCategory(menu.name||"");setMenu(null)}}>删除分类</button></>:<><strong>快速操作</strong><button onClick={add}>＋ 添加密码</button><button onClick={()=>{setMenu(null);setCategoryName("");setCategoryIcon("📁");setDialog("category")}}>＋ 添加分类</button></>}</div>}
  {dialog==="category"&&<Modal title="新建分类"><input autoFocus value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="例如：工作、金融、社交"/><label>图标 <input value={categoryIcon} onChange={e=>setCategoryIcon(e.target.value)} placeholder="输入 emoji，例如 💼"/></label><div className="iconChoices">{["▦","💼","💰","👥","💻","📁","🔑","☁️","🏠","🛒"].map(i=><button key={i} onClick={()=>setCategoryIcon(i)}>{i}</button>)}</div>{error&&<div className="error">{error}</div>}<div className="modalActions"><button className="cancelBtn" onClick={()=>setDialog("none")}>取消</button><button onClick={createCategory}>创建</button></div></Modal>}
  {dialog==="delete"&&<Modal title="永久删除密码">{multiSelected.length>0?<p>确定永久删除已选的 {multiSelected.length} 条密码吗？</p>:<p>确定删除“{current?.name||"此密码"}”吗？</p>}<p className="dangerText">此操作不可恢复。建议确认你不再需要该凭据。</p><div className="modalActions"><button className="cancelBtn" onClick={()=>setDialog("none")}>取消</button><button className="dangerBtn" onClick={multiSelected.length?applyBatchDelete:deleteCurrent}>永久删除</button></div></Modal>}
  {dialog==="discard"&&<Modal title="检测到未保存修改"><p>当前密码有未保存的修改。</p><p className="muted">切换密码、锁定或离开前，请选择是否保存。</p><div className="modalActions"><button className="cancelBtn" onClick={()=>setDialog("none")}>继续编辑</button><button className="secondary" onClick={()=>{const a=pendingAction;setPendingAction(null);setDialog("none");setDraft(null);setSelected(null);setEditMode(false);setDirty(false);void a?.()}}>放弃修改</button><button onClick={async()=>{const ok=await commitDraft();if(!ok)return;const a=pendingAction;setPendingAction(null);setDialog("none");void a?.()}}>保存修改</button></div></Modal>}
  {dialog==="history"&&<Modal title="修改记录"><p className="muted">仅记录哪些字段发生过变化，不保存字段的新旧具体内容。</p>{history.length?<div className="historyList">{history.map((h,i)=><div key={i}><b>{new Date(h.changedAt).toLocaleString()}</b><span>{h.fields.join("、")}</span></div>)}</div>:<p>暂无修改记录。</p>}<div className="modalActions"><button onClick={()=>setDialog("none")}>关闭</button></div></Modal>}
  {dialog==="credential"&&<Modal title={credentialKind==="export"?"验证本机 Vault 主密码":credentialKind==="import"?"验证原电脑 Vault 主密码":credentialKind==="restore"?"验证备份主密码":credentialKind==="backup"?"验证本机 Vault 主密码":"验证当前主密码"}><p className="muted">{credentialKind==="export"?"为了生成仅账号密码的加密数据，需要再次验证当前 Vault 主密码。主密码不会写入导出文件。":credentialKind==="import"?"这是跨电脑导入的安全验证：只有知道原电脑 Vault 主密码，才能解开导出文件中的数据密钥。主密码不会保存到新电脑。":credentialKind==="restore"?"导入完整备份前先验证备份对应的 Vault 主密码；验证失败不会覆盖当前 Vault。":credentialKind==="backup"?"完整备份属于高敏感级别数据。导出前需要再次验证当前 Vault 主密码；主密码不会写入备份文件。":"修改密保或主密码前，需要再次验证当前 Vault 主密码。验证通过后你可以选择只修改密保、只修改主密码，或同时修改。"}</p><input autoFocus type="password" value={credentialPassword} placeholder="Vault 主密码" onChange={e=>setCredentialPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void confirmCredential()}/>{error&&<div className="error">{error}</div>}<div className="modalActions"><button className="cancelBtn" onClick={()=>{setDialog("none");setPendingFile(null);setCredentialPassword("");setBackupData(null);setError("")}}>取消</button><button onClick={confirmCredential}>验证并继续</button></div></Modal>}
  {dialog==="securitySettings"&&<Modal title="密保及密码修改"><p className="muted">当前主密码验证通过。请选择要修改的内容；未勾选的项目保持不变。</p><label className="checkRow"><input type="checkbox" checked={changeMaster} onChange={e=>setChangeMaster(e.target.checked)}/> 修改主密码</label>{changeMaster&&<><input autoFocus type="password" placeholder="新主密码（至少 8 位，含数字/大小写字母/特殊符号）" value={newMaster} onChange={e=>setNewMaster(e.target.value)}/><input type="password" placeholder="再次输入新主密码" value={newConfirm} onChange={e=>setNewConfirm(e.target.value)}/><Meter value={score(newMaster)}/></>}<label className="checkRow"><input type="checkbox" checked={changeRecovery} onChange={e=>setChangeRecovery(e.target.checked)}/> 修改密保（会自动生成新的 Recovery Code）</label>{changeRecovery&&<div className="securitySettingsFields">{securityQuestions.map((q,i)=><label className="left" key={i}>问题 {i+1}<input value={q} onChange={e=>{const x=[...securityQuestions];x[i]=e.target.value;setSecurityQuestions(x)}}/><input value={securityAnswers[i]} placeholder="答案（不能为空，可使用中文）" onChange={e=>{const x=[...securityAnswers];x[i]=e.target.value;setSecurityAnswers(x)}}/></label>)}<p className="muted">修改密保后，旧 Recovery Code 立即失效，并自动生成新的 Recovery Code。新 Recovery Code 会尝试自动复制到剪贴板。</p></div>}{error&&<div className="error">{error}</div>}<div className="modalActions"><button className="cancelBtn" onClick={()=>{setVerifiedMasterPassword("");setDialog("none")}}>取消</button><button onClick={saveSecuritySettings}>保存修改</button></div></Modal>}
  {dialog==="backupRestore"&&<Modal title="导入完整备份"><p>备份验证成功：包含 <b>{backupData?.entries.length||0}</b> 条密码、<b>{backupData?.categories.length||0}</b> 个分类。</p><p className="muted">现在可以选择恢复方式。<b>合并</b>不会删除当前 Vault 的新数据；同一条目 ID 已存在时保留当前条目，备份中的新条目会追加。缺少的分类会一并加入。</p>{error&&<div className="error">{error}</div>}<div className="modalActions"><button className="cancelBtn" onClick={()=>{setDialog("none");setPendingFile(null);setCredentialPassword("");setBackupData(null);setError("")}}>取消</button><button className="secondary" onClick={()=>void restoreBackupMerge()}>合并到当前 Vault</button><button className="dangerBtn" onClick={()=>void restoreBackupReplace()}>替换当前 Vault</button></div></Modal>}
  {dialog==="import"&&<Modal title="导入账号密码"><p>文件已通过原 Vault 主密码验证并在本地解密。不会要求你把主密码写入导出文件。重复账号按“类型 + 用户名”判断；请逐条决定是否替换。</p><div className="historyList">{imported.map(e=>{const key=`${e.type}::${e.username}`.toLowerCase();const conflict=entries.some(x=>x.username&&e.username&&`${x.type}::${x.username}`.toLowerCase()===key);return <div key={e.id}><b>#{e.seq} · {e.name}</b><span>{e.type} · {e.username||"无用户名"}{conflict&&<> <select value={conflictChoice[e.id]||"skip"} onChange={ev=>setConflictChoice(a=>({...a,[e.id]:ev.target.value as "replace"|"skip"}))}><option value="skip">跳过</option><option value="replace">替换</option></select></>}</span></div>})}</div><div className="modalActions"><button className="cancelBtn" onClick={()=>setDialog("none")}>取消</button><button onClick={applyImport}>应用导入</button></div></Modal>}
  {dialog==="trash"&&<Modal title="回收站"><p className="muted">删除的密码会在 {trashDays} 天后自动清理。恢复后会回到当前 Vault。</p>{trash.length?<div className="historyList">{trash.map(e=><div key={e.id}><b>#{e.seq} · {e.name||"未命名"}</b><span>{e.type} · {e.username||e.email||"无账号信息"}<span className="trashActions"><button onClick={()=>restoreTrash(e.id)}>恢复</button><button className="dangerBtn" onClick={()=>purgeTrash(e.id)}>彻底删除</button></span></span></div>)}</div>:<p>回收站为空。</p>}<label>自动保留<select value={trashDays} onChange={e=>setTrashDays(+e.target.value)}><option value={7}>7 天</option><option value={14}>14 天</option><option value={21}>21 天</option><option value={30}>30 天</option></select></label><div className="modalActions"><button className="cancelBtn" onClick={()=>setDialog("none")}>关闭</button><button className="dangerBtn" onClick={()=>purgeTrash()}>清空回收站</button></div></Modal>}
  {dialog==="categoryEdit"&&<Modal title="编辑分类"><input autoFocus value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="分类名称"/><label>图标 <input value={categoryIcon} onChange={e=>setCategoryIcon(e.target.value)} /></label><div className="iconChoices">{["▦","💼","💰","👥","💻","📁","🔑","☁️","🏠","🛒"].map(i=><button key={i} onClick={()=>setCategoryIcon(i)}>{i}</button>)}</div>{error&&<div className="error">{error}</div>}<div className="modalActions"><button className="cancelBtn" onClick={()=>setDialog("none")}>取消</button><button onClick={updateCategory}>保存</button></div></Modal>}
  {dialog==="recovery"&&<RecoveryDialog questions={questions} answers={answers} setQuestions={setQuestions} setAnswers={setAnswers} onClose={()=>setDialog("none")} onSave={async()=>{try{const code=await invoke<string>("recovery_generate_code");await invoke("recovery_enable",{recoveryCode:code,recoveryQuestions:questions,recoveryAnswers:answers});await copyRecoveryCode(code);alert(`新的 Recovery Code：\n\n${code}\n\n旧 Recovery Code 已失效。请立即离线保存。`);setDialog("none")}catch(e){setError(String(e))}}}/>}
 </div>
}
function Editor({entry,entries,categories,types,tags,editMode,setEditMode,dirty,setDirty,showPass,setShowPass,onChange,onSave,onDelete,onHistory,targetHref,onAddType,onAddTag,onCancel}:{entry:Entry;entries:Entry[];categories:Category[];types:string[];tags:string[];editMode:boolean;setEditMode:(x:boolean)=>void;dirty:boolean;setDirty:(x:boolean)=>void;showPass:boolean;setShowPass:(x:boolean)=>void;onChange:(k:keyof Entry,v:any)=>void;onSave:()=>Promise<boolean>;onDelete:()=>void;onHistory:()=>void;targetHref:(v:string)=>string;onAddType:()=>void;onAddTag:()=>void;onCancel:()=>void}){
 const readOnly=!editMode;const days=entry.expiresAt?Math.max(0,Math.ceil((entry.expiresAt-now())/86400000)):0;
 const canOpenUrl=(v:string)=>/^https?:\/\//i.test(v)||/^www\./i.test(v)||/^\d{1,3}(?:\.\d{1,3}){3}(?::\d+)?(?:\/|$)/.test(v)||/^[a-z0-9.-]+\.[a-z]{2,}(?:\/|$)/i.test(v);
 const openSavedUrl=async(v:string)=>{try{await openUrl(targetHref(v))}catch(e){alert("无法打开网址："+String(e))}};
 const gen=()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*";const a=new Uint32Array(24);crypto.getRandomValues(a);onChange("password",Array.from(a,n=>c[n%c.length]).join(""))};
 const copy=async()=>{await navigator.clipboard.writeText(entry.password);setTimeout(()=>navigator.clipboard.writeText("").catch(()=>{}),30000)};
 const setExpiry=(v:string)=>{if(v==="never")onChange("expiresAt",null);else if(v==="30")onChange("expiresAt",expiryDate(30));else if(v==="90")onChange("expiresAt",expiryDate(90));else if(v==="180")onChange("expiresAt",expiryDate(180));};
 return <div className="form"><div className="formTop"><div className="titleBlock"><span>#{entry.seq} · {entry.type}</span><input className="title" readOnly={readOnly} value={entry.name} onChange={e=>onChange("name",e.target.value)}/></div>{!editMode&&<button onClick={()=>setEditMode(true)}>✎ 编辑密码</button>}{editMode&&<><button className="secondary" onClick={onCancel}>取消</button><button onClick={onSave}>保存</button></>}<button className="dangerBtn" onClick={onDelete}>删除</button></div>
  <div className="readonlyBanner">{readOnly?"只读查看模式：不会因为浏览而修改密码。":"编辑模式：修改完成后请点击“保存”。"}{dirty&&<b> · 有未保存修改</b>}</div>
  <label>账号类型<div className="inlineControl"><select disabled={readOnly} value={entry.type} onChange={e=>onChange("type",e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select>{editMode&&<button onClick={onAddType}>＋ 自定义类型</button>}</div></label>
  <div className="fieldGrid"><label>用户名<input readOnly={readOnly} value={entry.username} onChange={e=>onChange("username",e.target.value)}/></label><label>邮箱<input readOnly={readOnly} value={entry.email} onChange={e=>onChange("email",e.target.value)}/></label><label>手机号<input readOnly={readOnly} value={entry.phone} onChange={e=>onChange("phone",e.target.value)}/></label><label>平台昵称<input readOnly={readOnly} value={entry.nickname} onChange={e=>onChange("nickname",e.target.value)}/></label></div>
  <label>密码<div className="passrow"><input readOnly={readOnly} type={showPass?"text":"password"} value={entry.password} onChange={e=>onChange("password",e.target.value)}/><button onClick={()=>setShowPass(!showPass)}>👁</button>{editMode&&<button onClick={gen}>生成</button>}<button onClick={copy}>复制</button></div><Meter value={score(entry.password)}/></label>
  <label>网址 / IP / APP 名称<div className="urlrow"><input readOnly={readOnly} value={entry.url} placeholder="https://example.com / 192.168.1.1 / App 名称" onChange={e=>onChange("url",e.target.value)}/>{entry.url&&canOpenUrl(entry.url)&&<button onClick={()=>void openSavedUrl(entry.url)}>↗ 打开浏览器</button>}</div></label>
  <div className="fieldGrid"><label>分类<select disabled={readOnly} value={entry.category||"默认"} onChange={e=>onChange("category",e.target.value)}>{categories.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>收藏<input type="checkbox" disabled={readOnly} checked={entry.favorite} onChange={e=>onChange("favorite",e.target.checked)} /> ★ 收藏此密码</label><label>标签<div className="inlineControl"><input readOnly={readOnly} value={entry.tags.join("、")} placeholder="工作、高频使用、财务相关" onChange={e=>onChange("tags",e.target.value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean))}/>{editMode&&<button onClick={onAddTag}>＋ 自定义标签</button>}</div>{editMode&&<div className="tagChoices">{tags.map(t=><button key={t} className={entry.tags.includes(t)?"tagActive":""} onClick={()=>onChange("tags",entry.tags.includes(t)?entry.tags.filter(x=>x!==t):[...entry.tags,t])}>{entry.tags.includes(t)?"✓ ":""}{t}</button>)}</div>}</label></div>
  <div className="securityBox"><h3>时间信息</h3><div className="timeGrid"><div><span>最后修改时间</span><b>{new Date(entry.updatedAt).toLocaleString()}</b></div><div><span>密码状态</span><b className={entry.expiresAt&&days<=7?"dangerText":""}>{entry.expiresAt?days===0?"已过期":`${days} 天后过期`:"永不过期"}</b></div></div><label>密码过期设置<select disabled={readOnly} value={entry.expiresAt===null?"never":days<=31&&days>0?"custom":days===30?"30":days===90?"90":days===180?"180":"custom"} onChange={e=>setExpiry(e.target.value)}><option value="never">永不过期</option><option value="30">30 天</option><option value="90">90 天</option><option value="180">180 天</option><option value="custom">自定义（请使用日期）</option></select></label>{editMode&&<label>自定义到期日期<input type="date" value={dateInput(entry.expiresAt)} onChange={e=>onChange("expiresAt",e.target.value?new Date(e.target.value+"T23:59:59").getTime():null)}/></label>} {entry.expiresAt&&<small className={days<=7?"dangerText":"muted"}>提前 7 天提醒：{days<=7?"已触发，列表已标红":"未触发"}</small>}</div>
  <label>备注<textarea readOnly={readOnly} value={entry.notes} onChange={e=>onChange("notes",e.target.value)}/></label><div className="historyAction"><button className="secondary" onClick={onHistory}>查看最近 3 次修改记录</button></div>
 </div>
}
function Auth({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="auth"><div className="authCard"><div className="logo">🔐</div><h1>{title}</h1><p>{subtitle}</p>{children}</div></div>}
function Meter({value}:{value:number}){return <><div className="meter"><i style={{width:`${value}%`}}/></div><small>密码评分：{value}/100</small></>}
function Modal({title,children}:{title:string;children:React.ReactNode}){return <div className="overlay"><div className="modal"><h2>{title}</h2>{children}</div></div>}
function RecoveryDialog({questions,answers,setQuestions,setAnswers,onClose,onSave}:{questions:string[];answers:string[];setQuestions:(x:string[])=>void;setAnswers:(x:string[])=>void;onClose:()=>void;onSave:()=>Promise<void>}){return <div className="overlay"><div className="modal large"><h2>密保及密码修改</h2>{questions.map((q,i)=><label className="left" key={i}>问题 {i+1}<input value={q} onChange={e=>{const x=[...questions];x[i]=e.target.value;setQuestions(x)}}/><input value={answers[i]} placeholder="答案（不能为空，可使用中文）" onChange={e=>{const x=[...answers];x[i]=e.target.value;setAnswers(x)}}/></label>)}<p className="muted">建议使用高熵 Recovery Code。学校、出生地、生日等公开信息不应单独承担解锁责任。</p><div className="modalActions"><button className="cancelBtn" onClick={onClose}>取消</button><button onClick={onSave}>保存恢复设置</button></div></div></div>}
createRoot(document.getElementById("root")!).render(<App/>);
